origin_tag_id: 0
x_axis_align_tag_id: 1
marker_size_mm: 35.525
rmse_px: 0.9467713308089725
rmse_reprojection_px: 0.9467713308089725
calibrated_images_count: 16
tags:
  28:
    transform_matrix:
    - - -0.0058
      - 0.99998
      - 0.0
      - 114.62144
    - - -0.99968
      - -0.0058
      - 0.02449
      - 156.0051
    - - 0.02449
      - 0.00014
      - 0.9997
      - 151.5886
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 114.62
    - 156.01
    - 151.59
    rpy_deg:
    - 0.01
    - -1.4
    - -90.33
    is_origin: false
    is_dynamic_yaw: false
  0:
    transform_matrix:
    - - 0.99925
      - 0.0047
      - -0.03855
      - 0.0
    - - -0.00441
      - 0.99996
      - 0.00747
      - 0.0
    - - 0.03859
      - -0.00729
      - 0.99923
      - 405.0
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 0.0
    - 0.0
    - 405.0
    rpy_deg:
    - -0.42
    - -2.21
    - -0.25
    is_origin: true
    is_dynamic_yaw: true
  1:
    transform_matrix:
    - - 0.99992
      - 0.00834
      - -0.00964
      - 0.0
    - - -0.00831
      - 0.99996
      - 0.00266
      - 520.0
    - - 0.00967
      - -0.00258
      - 0.99995
      - 196.0
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 0.0
    - 520.0
    - 196.0
    rpy_deg:
    - -0.15
    - -0.55
    - -0.48
    is_origin: false
    is_dynamic_yaw: false
  18:
    transform_matrix:
    - - -0.00718
      - 0.99983
      - -0.01703
      - 113.4143
    - - -0.85953
      - 0.00254
      - 0.51108
      - 369.85722
    - - 0.51103
      - 0.01831
      - 0.85937
      - 140.77145
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 113.41
    - 369.86
    - 140.77
    rpy_deg:
    - 1.22
    - -30.73
    - -90.48
    is_origin: false
    is_dynamic_yaw: false
  19:
    transform_matrix:
    - - 0.01424
      - 0.99657
      - -0.08149
      - 113.17292
    - - -0.99982
      - 0.01315
      - -0.01395
      - 324.74856
    - - -0.01283
      - 0.08168
      - 0.99658
      - 151.30268
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 113.17
    - 324.75
    - 151.3
    rpy_deg:
    - 4.69
    - 0.74
    - -89.18
    is_origin: false
    is_dynamic_yaw: false
  20:
    transform_matrix:
    - - 0.01579
      - 0.83062
      - -0.55662
      - 115.65057
    - - -0.99981
      - 0.01937
      - 0.00054
      - 273.93657
    - - 0.01123
      - 0.55651
      - 0.83077
      - 138.42026
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 115.65
    - 273.94
    - 138.42
    rpy_deg:
    - 33.82
    - -0.64
    - -89.1
    is_origin: false
    is_dynamic_yaw: false
  21:
    transform_matrix:
    - - 0.84277
      - -0.00531
      - -0.53825
      - 0.93154
    - - 0.00105
      - 0.99997
      - -0.00822
      - 47.40199
    - - 0.53827
      - 0.00636
      - 0.84275
      - 169.62885
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 0.93
    - 47.4
    - 169.63
    rpy_deg:
    - 0.43
    - -32.57
    - 0.07
    is_origin: false
    is_dynamic_yaw: false
  22:
    transform_matrix:
    - - 0.99992
      - -0.00271
      - -0.01195
      - 49.66615
    - - 0.00218
      - 0.99899
      - -0.04481
      - 46.79209
    - - 0.01206
      - 0.04478
      - 0.99892
      - 182.97792
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 49.67
    - 46.79
    - 182.98
    rpy_deg:
    - 2.57
    - -0.69
    - 0.12
    is_origin: false
    is_dynamic_yaw: false
  23:
    transform_matrix:
    - - 0.99992
      - 0.01218
      - -0.00386
      - 49.94873
    - - -0.01229
      - 0.83475
      - -0.5505
      - -0.13766
    - - -0.00348
      - 0.5505
      - 0.83483
      - 169.68258
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 49.95
    - -0.14
    - 169.68
    rpy_deg:
    - 33.4
    - 0.2
    - -0.7
    is_origin: false
    is_dynamic_yaw: false
  24:
    transform_matrix:
    - - -0.9998
      - 0.00846
      - 0.01801
      - 47.62603
    - - 0.0024
      - -0.84725
      - 0.53119
      - 519.74943
    - - 0.01976
      - 0.53113
      - 0.84706
      - 94.58111
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 47.63
    - 519.75
    - 94.58
    rpy_deg:
    - 32.09
    - -1.13
    - 179.86
    is_origin: false
    is_dynamic_yaw: false
  25:
    transform_matrix:
    - - -0.99952
      - 0.0058
      - -0.03032
      - 48.14908
    - - -0.00677
      - -0.99947
      - 0.03184
      - 473.0486
    - - -0.03011
      - 0.03203
      - 0.99903
      - 106.65202
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 48.15
    - 473.05
    - 106.65
    rpy_deg:
    - 1.84
    - 1.73
    - -179.61
    is_origin: false
    is_dynamic_yaw: false
  26:
    transform_matrix:
    - - -0.84926
      - -0.00175
      - -0.52797
      - 0.22021
    - - 0.00728
      - -0.99994
      - -0.00839
      - 473.58183
    - - -0.52792
      - -0.01097
      - 0.84922
      - 94.56428
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 0.22
    - 473.58
    - 94.56
    rpy_deg:
    - -0.74
    - 31.87
    - 179.51
    is_origin: false
    is_dynamic_yaw: false
  27:
    transform_matrix:
    - - -0.00716
      - 0.99997
      - -0.00324
      - 113.11058
    - - -0.85135
      - -0.0044
      - 0.52458
      - 201.97363
    - - 0.52455
      - 0.00651
      - 0.85136
      - 138.37061
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 113.11
    - 201.97
    - 138.37
    rpy_deg:
    - 0.44
    - -31.64
    - -90.48
    is_origin: false
    is_dynamic_yaw: false
  29:
    transform_matrix:
    - - 0.00823
      - 0.83953
      - -0.54325
      - 116.60682
    - - -0.99973
      - 0.01864
      - 0.01367
      - 107.36233
    - - 0.02161
      - 0.543
      - 0.83946
      - 139.33615
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    position_mm:
    - 116.61
    - 107.36
    - 139.34
    rpy_deg:
    - 32.9
    - -1.24
    - -89.53
    is_origin: false
    is_dynamic_yaw: false
world_anchor:
  origin_tag_id: 0
  origin_xyz_mm:
  - 0.0
  - 0.0
  - 405.0
  align_tag_id: 1
  align_xyz_mm:
  - 0.0
  - 520.0
  - 196.0
  scale_factor: 0.710508
  ba_baseline_mm: 788.773
  world_baseline_mm: 560.429
  real_marker_size_mm: 35.525
